[package]
name = "sods-zk-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.0", default-features = false, features = ["guest"] }
sods-core = { path = "../../sods-core" }
serde = { version = "1.0", features = ["derive"] }
