[package]
name = "sods-zk"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["methods"]

[dependencies]
risc0-zkvm = "1.0"
sods-core = { path = "../sods-core" }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"

[build-dependencies]
risc0-build = "1.0"
